In [ ]:
import numpy as np
#RANDOM MODULE IS SUB-PACKAGE OF NUMPY

In [ ]:
A=np.random.rand(1)
print(A)

[0.60410095]


In [ ]:
A=np.random.rand(8,4)
print(A)

[[0.26785451 0.49268568 0.25565874 0.7165777 ]
 [0.20252077 0.01081789 0.11033059 0.56995956]
 [0.3490693  0.65776322 0.83340642 0.21277168]
 [0.9234705  0.59503651 0.70390257 0.99083671]
 [0.67132672 0.92299117 0.70235862 0.16612313]
 [0.46309177 0.19811583 0.17212267 0.41035594]
 [0.16042669 0.88088817 0.63390012 0.6654028 ]
 [0.41706251 0.83981689 0.20098516 0.21093489]]


In [ ]:
A=10*np.random.rand(8,4)
print(A)

[[3.95424946 6.44181472 5.29712061 4.89495717]
 [2.76000692 2.10274238 1.67010809 7.59570607]
 [2.55546552 6.89738802 9.60112931 5.23554372]
 [9.3513419  0.73084286 6.72493637 1.76306842]
 [2.10979718 9.00044972 1.91573392 8.78846116]
 [8.30585645 0.71305653 2.64172039 7.82827317]
 [8.94585609 9.63859965 2.20163786 2.03550442]
 [7.27627616 4.65167102 5.42037548 2.24659813]]


In [ ]:
A=np.floor(10*np.random.rand(8,4))
print(A)

[[1. 8. 3. 9.]
 [4. 6. 8. 1.]
 [3. 1. 2. 2.]
 [7. 5. 6. 1.]
 [1. 2. 2. 9.]
 [7. 8. 7. 4.]
 [3. 5. 5. 6.]
 [4. 8. 3. 2.]]


In [ ]:
A=np.arange(1,33).reshape(8,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.vsplit(A,4)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]),
 array([[17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
np.vsplit(A,(2,6)) #split it after 2rd row and 6th row

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]),
 array([[25, 26, 27, 28],
        [29, 30, 31, 32]])]

In [ ]:
#create an array with 4 rows and 8 columns
B=np.arange(1,33).reshape(4,8)
print(B)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


In [ ]:
np.hsplit(B,4)

[array([[ 1,  2],
        [ 9, 10],
        [17, 18],
        [25, 26]]),
 array([[ 3,  4],
        [11, 12],
        [19, 20],
        [27, 28]]),
 array([[ 5,  6],
        [13, 14],
        [21, 22],
        [29, 30]]),
 array([[ 7,  8],
        [15, 16],
        [23, 24],
        [31, 32]])]

In [ ]:
np.hsplit(B,(3,7))

[array([[ 1,  2,  3],
        [ 9, 10, 11],
        [17, 18, 19],
        [25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]]),
 array([[ 8],
        [16],
        [24],
        [32]])]

In [ ]:
np.pi

3.141592653589793

In [ ]:
A=[np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
B=np.rad2deg(A)
print(B)

[ 45.  60.  90. 180.]


In [ ]:
np.deg2rad(B)

array([0.78539816, 1.04719755, 1.57079633, 3.14159265])

In [ ]:
np.sin(1)

0.8414709848078965

In [ ]:
np.tan(45)

1.6197751905438615

In [ ]:
np.cos(1)

0.5403023058681398

In [ ]:
np.cos(45)

0.5253219888177297

Statistics

In [ ]:
 st=np.array([23,45,67,89,21,34])


In [ ]:
np.mean(st)

46.5

In [ ]:
np.median(st)

39.5

In [ ]:
np.std(st)

24.452334585202017

In [ ]:
np.var(st)

597.9166666666666

In [ ]:
C=np.arange(1,5).reshape(2,2)
print(C)

[[1 2]
 [3 4]]


In [ ]:
np.linalg.inv(C)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
C=np.arange(1,25).reshape(6,4)
print(C)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
print(np.argmax(C))

23


In [ ]:
C=np.floor(10*np.random.rand(24).reshape(6,4))
print(C)

[[0. 5. 6. 6.]
 [6. 5. 5. 7.]
 [8. 9. 1. 1.]
 [9. 8. 6. 4.]
 [2. 6. 5. 2.]
 [0. 3. 9. 2.]]


In [ ]:
C=10*np.random.rand(24).reshape(6,4)
print(C)

[[0.79491103 7.04632426 6.63248193 2.23486017]
 [2.80573715 0.41441517 7.44476635 9.69962445]
 [6.81804374 6.18970033 7.6197838  6.35994635]
 [2.08616386 6.5605408  2.90793658 2.54981365]
 [0.39580167 3.08532124 7.30190398 8.63250082]
 [9.20185717 1.82203467 5.00441596 8.81666935]]


In [ ]:
print(np.argmax(C,axis=1))

[1 3 2 1 3 0]


In [ ]:
print(np.argmax(C,axis=0))

[5 0 2 1]


In [ ]:
print(np.argmin(C))

16


In [ ]:
print(np.argmin(C,axis=0))

[4 1 3 0]


In [ ]:
print(np.argmin(C,axis=1))

[0 1 1 0 0 1]


Searching

In [ ]:
A=np.array([34,12,57,24,42,11])
print(np.where(A%2==0))       #printing 2 divisible numbers of remainder 0

(array([0, 1, 3, 4]),)


In [ ]:
A=np.array([34,12,57,24,42,11])  #printing odd numbers
print(np.where(A%2!=0))

(array([2, 5]),)


In [ ]:
B=np.array([24,16,7,17,54,60])
print(np.where(B%6==0))

(array([0, 4, 5]),)


In [ ]:
a=np.array([3,4,5,6,7,8,9,10])#sorted array is to  be searched index position
x=np.searchsorted(a,8)
print(x)

5


In [ ]:
a=np.array([35,4,52,16,7,18,9,50])
x=np.searchsorted(a,4) #unsorted array
print(x)

0


In [ ]:
#sorting array
import numpy as np
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))
#2nd example
arr=np.array(['TRUE','FALSE','TRUE'])
print(np.sort(arr))

['apple' 'banana' 'cherry']
['FALSE' 'TRUE' 'TRUE']


In [ ]:
#2d sort -sorting happens with in the column
arr=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [ ]:
#filter
arr=np.array([40,43,50,44,67,78])
flit=np.where(arr%2==0)
print(flit)

(array([0, 2, 3, 5]),)


In [ ]:
arr[flit]

array([40, 50, 44, 78])

In [ ]:
#iterating through two arrays
names=np.array(["Reethi","Tharani","sriya","jahnavi"])
initials=np.array(["V","R","S","K"])
for i ,j in zip(initials,names):
   print(i,".",j)

V . Reethi
R . Tharani
S . sriya
K . jahnavi


In [ ]:
#multiplication of two arrays
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.multiply(a1,a2)
print(n)

[ 200  420  660  920 1200 1500]


In [ ]:

#division of two arrays
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.divide(a1,a2)
print(n)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [ ]:
#modulo of two  array
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.mod(a1,a2)
print(n)

[10 20  8 17  2 10]


In [ ]:
#divmod of two array
a1=np.array([10,20,30,40,50,60])
a2=np.array([20,21,22,23,24,25])
n=np.divmod(a1,a2)
print(n)

(array([0, 0, 1, 1, 2, 2]), array([10, 20,  8, 17,  2, 10]))


In [ ]:
#Logarithms
a=1.2
print(np.log(a)) #natural log e

0.1823215567939546


In [ ]:
a=np.array([1,1.2,3,4])
print(np.log(a)) #natural log e

[0.         0.18232156 1.09861229 1.38629436]


In [ ]:
a=1.2
print(np.log2(a)) #log base 2

0.2630344058337938


In [ ]:
a=1.2
print(np.log10(a)) #log base 10

0.07918124604762482


In [ ]:
#cumulative product
a2=np.array([5,6,7,10])
x=np.cumprod(a2)
print(x)

[   5   30  210 2100]


In [ ]:
#cumulative sum
a2=np.array([1,2,3,4,5])
x=np.cumsum(a2)
print(x)

[ 1  3  6 10 15]


In [ ]:
#difference
a=np.array([10,15,25,30])
x=np.diff(a)
print(x)

[ 5 10  5]


In [ ]:
#LCM
n1=455
n2=665
x=np.lcm(n1,n2)
print(x)

8645


In [ ]:
#GCD
n1=455
n2=665
c=np.gcd(n1,n2)
print(c)

35


In [ ]:
#HCF
n1=25
n2=50
x=np.gcd(n1,n2)
print(x)

25


In [ ]:
a=np.array([12,15,60])
c=np.lcm.reduce(a)
print(c)