In [ ]:
#importing
import numpy as np

In [ ]:
!pip install numpy

Arrays

In [ ]:
#creating 1D array
A=np.array([2,3,4,5])
print(type(A))

<class 'numpy.ndarray'>


In [ ]:
#creating a 2D array
B=np.array([[2,3,4],[7,8,9]])
print(B)

[[2 3 4]
 [7 8 9]]


In [ ]:
#creating a 3D array -rows,columns,groups
C=np.array([[[2,3,4],[3,4,5]],[[6,7,8],[7,8,9]]])
print(C)

[[[2 3 4]
  [3 4 5]]

 [[6 7 8]
  [7 8 9]]]


In [ ]:
#checking dimensions
print(A.ndim)
print(B.ndim)
print(C.ndim)

1
2
3


In [ ]:
D=np.ones((3,2))
print(D)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
